### ISSUE TITLE
Suggestion: 1.14.4 needs update to latest Forge

### ISSUE THREAD

**Issue by Wissi** [itsmeow/QuickSpawns#2]
It's an awesome mod, but it needs to be ported to the current forge 1.14.4?

```
[Server thread/WARN] [net.minecraftforge.fml.server.ServerModLoader/LOADING]: File quickspawns-1.0.0.jar is for an older version of Forge and cannot be loaded
```
Hope you can update soon so we can add to our servers.

Thanks.

**Comment by itsmeow** [comment]
It is updated. You have the 1.12 version.

**Comment by itsmeow** [comment]
god dammit wrong issue tracker, whatever, I'll update when I get to it, stop asking
